# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uj0GmpMz1Q_2MKIpdR_E2QI06OzvrTLs
"""

!pip install yfinance mftool

import yfinance as yf
import pandas as pd
from mftool import Mftool

def get_stock_data(ticker: str, period: str = "1y") -> pd.DataFrame:
    df = yf.download(ticker, period=period, auto_adjust=True)
    df.dropna(inplace=True)
    return df

def get_stock_info(ticker: str) -> dict:
    stock = yf.Ticker(ticker)
    return stock.info

def get_mutual_fund_data(scheme_code: str):
    mf = Mftool()
    return mf.get_scheme_historical_nav(scheme_code, as_Dataframe=True)

def get_all_mf_schemes() -> dict:
    mf = Mftool()
    return mf.get_scheme_codes()

def enrich_stock_data(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
    df["daily_return"] = df["Close"].pct_change()
    df["volatility_30d"] = df["daily_return"].rolling(30).std() * (252 ** 0.5)
    df["SMA_20"] = df["Close"].rolling(20).mean()
    df["SMA_50"] = df["Close"].rolling(50).mean()
    return df.dropna()

df = get_stock_data("RELIANCE.NS", "3mo")
print("Stock data loaded:", df.shape)
print(df.tail(3))

df_enriched = enrich_stock_data(df)
print("Enriched data:", df_enriched.columns.tolist())
print(df_enriched[["Close", "daily_return", "volatility_30d", "SMA_20", "SMA_50"]].tail(3))

info = get_stock_info("TCS.NS")
print("Stock info keys:", list(info.keys())[:10])
print("Sector:", info.get("sector"))
print("Market Cap:", info.get("marketCap"))

nav = get_mutual_fund_data("119551")
print("Mutual fund NAV loaded")
print(nav.head(3))
