# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xpr6xb-ftDCb33aJmBM1hy14kw_uL14t
"""

import pandas as pd
import numpy as np
from data_loader import get_stock_data, enrich_stock_data, get_mutual_fund_data, get_all_mf_schemes

STOCK_TICKERS = ['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS']

MF_SCHEME_CODES = {
    '119551': 'Axis Bluechip Fund',
    '120503': 'Mirae Asset Large Cap Fund',
    '125494': 'Parag Parikh Flexi Cap Fund',
}

def load_and_clean_all_stocks(tickers=STOCK_TICKERS, period='1y') -> pd.DataFrame:
    frames = []
    for ticker in tickers:
        df = get_stock_data(ticker, period)
        df = enrich_stock_data(df)

        # Flatten multi-level columns if present
        df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

        # Standardize column names to lowercase
        df.columns = df.columns.str.lower()

        # Add ticker and reset index
        df['ticker'] = ticker
        df = df.reset_index()
        df.rename(columns={'Date': 'date', 'close': 'close'}, inplace=True)

        frames.append(df)

    return pd.concat(frames, ignore_index=True)

def load_raw_mutual_funds(scheme_codes=MF_SCHEME_CODES) -> pd.DataFrame:
    frames = []
    for code, name in scheme_codes.items():
        df = get_mutual_fund_data(code)
        df = df.reset_index()
        df['scheme_code'] = code
        df['scheme_name'] = name
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def clean_mutual_funds(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = df.columns.str.strip().str.lower()

    # Convert NAV to numeric
    df['nav'] = pd.to_numeric(df['nav'], errors='coerce')
    df['daychange'] = pd.to_numeric(df['daychange'], errors='coerce')

    # Parse date
    df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')
    df.sort_values(['scheme_name', 'date'], inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Compute returns per scheme
    df['daily_return'] = df.groupby('scheme_name')['nav'].pct_change() * 100

    # Add synthetic risk/category columns for dashboard compatibility
    df['category'] = 'Equity'
    df['risk_level'] = 'Moderate'
    df['returns_1yr'] = df.groupby('scheme_name')['nav'].transform(
        lambda x: ((x.iloc[-1] / x.iloc[0]) - 1) * 100 if len(x) > 1 else np.nan
    )
    df['returns_3yr'] = np.nan
    df['returns_5yr'] = np.nan
    df['sd'] = df.groupby('scheme_name')['daily_return'].transform('std')

    df.dropna(subset=['nav'], inplace=True)
    return df

stocks = load_and_clean_all_stocks()
print(stocks.columns.tolist())
print(stocks.head(2))
